/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    QBtn: typeof import('quasar/src/components/btn/QBtn.js')['default']
    QCard: typeof import('quasar/src/components/card/QCard.js')['default']
    QCardSection: typeof import('quasar/src/components/card/QCardSection.js')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
